workshop2/M3Persistence/M3SuperHeroManager/Models/SuperHero.cs
using M3SuperHeroManager.Helpers;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace M3SuperHeroManager.Models
{
    public enum HeroSide
    {
        [Display(Name = "Civil")]
        civil = 0,
        [Display(Name = "Good")]
        good = 1,
        [Display(Name = "Bad")]
        bad = 2,
    }

    [ModelBinder(BinderType = typeof(SuperHeroModelBinder))]
    public class SuperHero
    {
        [Key]
        public string Id { get; set; }

        [Required]
        [StringLength(50)]
        [ShowTable]
        public string Name { get; set; }

        [Required]
        [Range(1,10)]
        [ShowTable]
        public int Power { get; set; }

        [ShowTable]
        public bool Alien { get; set; }

        [Required]
        [ShowTable]
        public HeroSide Side { get; set; }

        [StringLength(200)]
        public string? ImageFileName { get; set; }

        
        public string? ContentType { get; set; }

        public byte[]? Data { get; set; }

        public SuperHero()
        {
            Id = Guid.NewGuid().ToString();
        }
    }
}

workshop2/M3Persistence/M3SuperHeroManager/Models/SuperHeroCreateViewModel.cs
namespace M3SuperHeroManager.Models
{
    public class SuperHeroCreateViewModel
    {
        public SuperHero Hero { get; set; }
        public IEnumerable<SuperHero> Others { get; set; }
    }
}

workshop2/M3Persistence/M3SuperHeroManager/Controllers/HeroController.cs
using M3SuperHeroManager.Data;
using M3SuperHeroManager.Models;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using System.IO;

namespace M3SuperHeroManager.Controllers
{
    public class HeroController : Controller
    {
        ISuperHeroRepository repository;

        public HeroController(ISuperHeroRepository repository)
        {
            this.repository = repository;
        }

        [OutputCache(Duration = 5, VaryByParam = "none")]
        public IActionResult Index()
        {
            return View(this.repository.Read());
        }

        [OutputCache(Duration = 5, VaryByParam = "none")]
        [HttpGet]
        public IActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult Create(SuperHero hero)
        {
            if (!ModelState.IsValid)
            {
                return View(hero);
            }
            repository.Create(hero);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(string name)
        {
            repository.Delete(name);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Update(string name)
        {
            var hero = repository.Read(name);
            return View(hero);
        }

        [HttpPost]
        public IActionResult Update(SuperHero hero)
        {
            if (!ModelState.IsValid)
            {
                return View(hero);
            }
            repository.Update(hero);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult GetImage(string id)
        {
            var hero = repository.ReadFromId(id);
            if (hero.ContentType.Length > 3)
            {
                return new FileContentResult(hero.Data, hero.ContentType);
            }
            else
            {
                return BadRequest();
            }
            
        }

        public IActionResult Error()
        {
            var exceptionHandlerPathFeature =
            HttpContext.Features.Get<IExceptionHandlerPathFeature>();
            var msg = exceptionHandlerPathFeature.Error.Message;
            return View("Error", msg);
        }



    }
}

workshop2/M3Persistence/M3SuperHeroManager/Views/Hero/Create.cshtml
@using M3SuperHeroManager.Models
@model SuperHero


@section head{
    <title>Create new Hero!</title>
    <meta name="keywords" content="create, hero creator, heroeditor">
}

<h1>Create your Hero</h1>

<form action="create" method="post" enctype="multipart/form-data" style="display: flex; flex-direction: column">
    @Html.LabelFor(t => t.Name)
    @Html.EditorFor(t => t.Name)
    @Html.ValidationMessageFor(t => t.Name)

    @Html.LabelFor(t => t.Power)
    @Html.EditorFor(t => t.Power)
    @Html.ValidationMessageFor(t => t.Power)

    @Html.LabelFor(t => t.Alien)
    @Html.CheckBoxFor(t => t.Alien)

    @Html.LabelFor(t => t.Side)   
    @Html.DropDownListFor(t => t.Side, Html.GetEnumSelectList(typeof(HeroSide)))

    
    <label>Picture</label>
    <input type="file" name="picturedata"/>

    <input type="submit" value="Create" /> 

</form>

workshop2/M3Persistence/M3SuperHeroManager/Views/Hero/Index.cshtml
@using M3SuperHeroManager.Helpers
@using M3SuperHeroManager.Models
@model IEnumerable<SuperHero>
@inject TableBuilder tb

@section head{
    <title>List your Heroes!</title>
    <meta name="keywords" content="list, heroes, herocollection">
}

<h1>SuperHeroes</h1>

@Html.Raw(tb.BuildTable(Model))

<hr />
<table>
    <tr>
        <th>Picture</th>
        <th>Name</th>
        <th>Power</th>
        <th>Alien?</th>
        <th>Side</th>
        <th>Actions</th>
    </tr>
    @foreach(var item in Model){
        @:<tr>
        @: <td><img height="100" src="@Url.Action("GetImage", "Hero", new {id = item.Id})"/></td>
        @: <td>@item.Name</td>
        @: <td>@item.Power</td>
        @: <td>@item.Alien</td>
        @: <td>@item.Side</td>
        @: <td>
        @:    <a href="/hero/delete?name=@item.Name">Delete</a>
        @:    <a href="/hero/update?name=@item.Name">Update</a>
        @: </td>
        @: </tr>
    }
</table>



<a href="/hero/create">Create new hero</a>

workshop2/M3Persistence/M3SuperHeroManager/Views/Hero/Update.cshtml
@using M3SuperHeroManager.Models
@model SuperHero

@section head{
    <title>Update your Hero!</title>
}

<h1>Update your Hero (@Model.Name)</h1>

<form action="update" method="post" style="display: flex; flex-direction: column">
    @*@Html.LabelFor(t => t.Name)
    @Html.EditorFor(t => t.Name)
    @Html.ValidationMessageFor(t => t.Name)*@
    @Html.HiddenFor(t => t.Name)

    @Html.LabelFor(t => t.Power)
    @Html.EditorFor(t => t.Power)
    @Html.ValidationMessageFor(t => t.Power)

    @Html.LabelFor(t => t.Alien)
    @Html.CheckBoxFor(t => t.Alien)

    @Html.LabelFor(t => t.Side)   
    @Html.DropDownListFor(t => t.Side, Html.GetEnumSelectList(typeof(HeroSide)))
   

    <input type="submit" value="Update" /> 

</form>

workshop2/M3Persistence/M3SuperHeroManager/Views/Shared/Navbar.cshtml
@using M3SuperHeroManager.Data
@inject ISuperHeroRepository repo
<nav>
        <a href="/Hero/Index">List Heroes (@repo.Read().Count())</a>
        <a href="/Hero/Create">New Hero</a>
</nav>

workshop2/M3Persistence/M3SuperHeroManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @RenderSection("head", false)
</head>
<body>
    @Html.Partial("Navbar")
    @RenderBody()
</body>
</html>